In [ ]:
#Shubha Ghimire
#ID- 2430050

import numpy as np

In [ ]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([[1,2,3,4]])
c = np.array([[1,2,3,4],[5,6,7,8]])
a.shape
c.shape

(2, 4)

In [ ]:
a = np.array([[1,2,3,4],[2,3,4,5]])
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
b = np.array([[4,5,6,7],[6,8,4,5]])
b

array([[4, 5, 6, 7],
       [6, 8, 4, 5]])

In [ ]:
c = np.concatenate((a,b))
c

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 8, 4, 5]])

In [ ]:
d = np.stack((a,b) , axis =1)
d

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[2, 3, 4, 5],
        [6, 8, 4, 5]]])

In [ ]:
e = np.vstack((a,b))
e

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 8, 4, 5]])

In [ ]:
#1
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")


Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [ ]:
#1
# prompt: Initialize an empty array with size 2X2.

import numpy as np

empty_array = np.empty((2, 2))
empty_array

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

In [ ]:
#2
#Initialize an all one array with size 4X2.

import numpy as np

one_array = np.ones((4, 2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:

#3
#Return a new array of given shape and type, filled with fill value.{Hint: np.full}
full_array = np.full((3, 3), 5)
full_array

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#4
# prompt: Return a new array of zeros with same shape and type as a given array.{Hint:

import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6]])

zeros_array = np.zeros_like(original_array)

zeros_array

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
#5
# prompt: Return a new array of ones with same shape and type as a given array.{Hint:

import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6]])

ones_array = np.ones_like(original_array)

ones_array

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#6
# For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

new_list = [1,2,3,4]
numpy_array = np.array(new_list)
numpy_array


array([1, 2, 3, 4])

Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
#1
# Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np
array = np.arange(10,50)
array




array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#2
# Create a 3X3 matrix with values ranging from 0 to 8.
# {Hint:look for np.reshape()}

array = np.arange(9).reshape(3,3)
array


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#3
# Create a 3X3 identity matrix.{Hint:np.eye()}

array = np.eye(3,3)
array


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#4
# Create a random array of size 30 and find the mean of the array.
# {Hint:check for np.random.random() and array.mean() function}
random_array = np.random.random(30)
mean_array = np.mean(random_array)
mean_array

0.4734800738501922

In [ ]:
#5
# Create a 10X10 array with random values and find the minimum and maximum values.
random_array = np.random.rand(10, 10)

min_array = np.min(random_array)
max_array = np.max(random_array)
print(f"Minimum value: {min_array}")
print(f"Maximum value: {max_array}")


Minimum value: 0.019569851416752604
Maximum value: 0.9869779989679872


In [ ]:
# 6
# Create a zero array of size 10 and replace 5th element with 1.
import numpy as np

zero_array = np.zeros(10)
zero_array[4] = 1  # Replace the 5th element (index 4) with 1

zero_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#7
# Reverse an array arr = [1,2,0,0,4,0]

array = [1,2,0,0,4,0]
array.reverse()
array

[0, 4, 0, 0, 2, 1]

In [ ]:
#8
# Create a 2d array with 1 on border and 0 inside.
import numpy as np
rows = 5
cols = 4
array = np.ones((rows, cols))
array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#9
# Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1

print(checkerboard) # To see the output, run the code.

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


 Problem- 3: Array Operations:

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [ ]:
#1
# Add two array

x = np.array([[1,2],[3,5]]) ,
y = np.array([[5,6],[7,8]]) ,
add = np.add(x,y)
add



array([[[ 6,  8],
        [10, 13]]])

In [ ]:
# 2
# Substract two array
v = np.array([9,10]) ,
w = np.array([11,12])
sub = np.subtract(v,w)
sub


array([[-2, -2]])

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

x_multiplied = x * 2
y_multiplied = y * 2
v_multiplied = v * 2
w_multiplied = w * 2

print("x multiplied by 2:\n", x_multiplied)
print("y multiplied by 2:\n", y_multiplied)
print("v multiplied by 2:\n", v_multiplied)
print("w multiplied by 2:\n", w_multiplied)


x multiplied by 2:
 [[ 2  4]
 [ 6 10]]
y multiplied by 2:
 [[10 12]
 [14 16]]
v multiplied by 2:
 [18 20]
w multiplied by 2:
 [22 24]


In [ ]:
#4
# Find the square of each element of the array.

import numpy as np

x_square = np.square(x),
y_square = np.square(y),
v_square = np.square(v),
w_square = np.square(w),

print("Square of x " , x_square),
print("Square of y " , y_square),
print("Square of v " , v_square),
print("Square of w " , w_square)

Square of x  (array([[ 1,  4],
       [ 9, 25]]),)
Square of y  (array([[25, 36],
       [49, 64]]),)
Square of v  (array([ 81, 100]),)
Square of w  (array([121, 144]),)


In [ ]:
#5
# Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_v_w = np.dot(v, w),
dot_x_v = np.dot(x, v),
dot_x_y = np.dot(x,y),

print("Dot product of v and w:",dot_v_w),
print("Dot product of x and v:", dot_x_v),
print("Dot product of x and y:\n", dot_x_y)

Dot product of v and w: (219,)
Dot product of x and v: (array([29, 77]),)
Dot product of x and y:
 (array([[19, 22],
       [50, 58]]),)


In [ ]:
#6
#  Concatenate x(and)y along row and Concatenate v(and)w along column.
#  {Hint:try np.concatenate() or np.vstack() functions.

concatenated_xy = np.concatenate((x, y), axis=0)
concatenated_vw = np.vstack((v, w))
print("Concatenated x and y along rows:\n", concatenated_xy)
print("Concatenated v and w along columns:\n", concatenated_vw)


Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 10]
 [11 12]]


Concatenated_xy = np.concatenate((x, y),) why i am getting error ?

The error occurs because the np.concatenate() function requires the axis parameter.Axis is set to 0, which means concatenation along the first axis (rows)

Problem 4

In [ ]:


# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1 = I:\n", identity_matrix)

# 2. Prove AB = BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB == BA:", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)
print("(AB)^T == B^T A^T:", np.array_equal(AB_T, BT_AT))



A * A^-1 = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA: False
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T A^T: True


A * A⁻¹:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A * A⁻¹ equal to the identity matrix?
True


In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure the time taken for element-wise addition
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()

print("Time taken for element-wise addition using Python lists:", end_time - start_time, "seconds")


Time taken for element-wise addition using Python lists: 0.26267290115356445 seconds


In [ ]:
import numpy as np
import time

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time, "seconds")


Time taken for element-wise addition using NumPy arrays: 0.024696826934814453 seconds


In [ ]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()

print("Time taken for element-wise multiplication using Python lists:", end_time - start_time, "seconds")


Time taken for element-wise multiplication using Python lists: 0.3301560878753662 seconds


In [ ]:
import numpy as np
import time

array1 = np.arange(1000000)
array2 = np.arange(1000000)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time, "seconds")


Time taken for element-wise multiplication using NumPy arrays: 0.009035587310791016 seconds


In [ ]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()

print("Dot product using Python lists:", dot_product_list)
print("Time taken using Python lists:", end_time - start_time, "seconds")


Dot product using Python lists: 333332833333500000
Time taken using Python lists: 0.17689275741577148 seconds


In [ ]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
end_time = time.time()

print("Dot product using Python lists:", dot_product_list)
print("Time taken using Python lists:", end_time - start_time, "seconds")


Dot product using Python lists: 333332833333500000
Time taken using Python lists: 0.2749598026275635 seconds


In [ ]:
import time

matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2)] for matrix1_row in matrix1]
end_time = time.time()

print("Time taken for matrix multiplication using Python lists:", end_time - start_time, "seconds")


Time taken for matrix multiplication using Python lists: 242.73483729362488 seconds


In [ ]:
import numpy as np
import time

array1 = np.arange(1000000).reshape(1000, 1000)
array2 = np.arange(1000000).reshape(1000, 1000)

start_time = time.time()
result_array = np.dot(array1, array2)
end_time = time.time()

print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time, "seconds")


Time taken for matrix multiplication using NumPy arrays: 2.639695405960083 seconds
