In [ ]:
#Name: Shubha Ghimire
#ID: 2430050

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

dataSet=pd.read_csv("/content/drive/MyDrive/Concept and Technology of AI/student.csv")
headData=dataSet.head()
print("This is the most top data : \n" ,headData,"\n")

This is the most top data : 
    Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62 



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
tailData=dataSet.tail()
print("This is the most button data :\n" ,tailData,"\n" )

This is the most button data :
      Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72 



In [ ]:
dataInfo=dataSet.info
print("Basic info of the given dataset:" ,dataInfo,"\n")

Basic info of the given dataset: <bound method DataFrame.info of      Math  Reading  Writing
0      48       68       63
1      62       81       72
2      79       80       78
3      76       83       79
4      59       64       62
..    ...      ...      ...
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

[1000 rows x 3 columns]> 



In [ ]:
dataDesc=dataSet.describe()
print("Description of the given dataset : \n" ,dataDesc,"\n")

Description of the given dataset : 
               Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000 



In [ ]:
X = dataSet[['Math', 'Reading']]
Y = dataSet['Writing']

print("Features (X):")
print(X)

print("\nTarget (Y):")
print(Y)

Features (X):
     Math  Reading
0      48       68
1      62       81
2      79       80
3      76       83
4      59       64
..    ...      ...
995    72       74
996    73       86
997    89       87
998    83       82
999    66       66

[1000 rows x 2 columns]

Target (Y):
0      63
1      72
2      78
3      79
4      62
       ..
995    70
996    90
997    94
998    78
999    72
Name: Writing, Length: 1000, dtype: int64


In [ ]:
X = dataSet[['Math', 'Reading']].to_numpy()
Y_actual = dataSet['Writing'].to_numpy()
X = X.T
d = X.shape[0]
W = np.random.rand(d, 1)
Y_pred = np.dot(W.T, X).T
print("Weight Vector (W):")
print(W)

print("\nFeature Matrix (X):")
print(X)

print("\nPredicted Target Vector (Y):")
print(Y_pred)
print("\nShapes:")
print("W:", W.shape)
print("X:", X.shape)
print("Y (predicted):", Y_pred.shape)

Weight Vector (W):
[[0.56794178]
 [0.65375783]]

Feature Matrix (X):
[[48 62 79 ... 89 83 66]
 [68 81 80 ... 87 82 66]]

Predicted Target Vector (Y):
[[ 71.71673826]
 [ 88.16677506]
 [ 97.16802753]
 [ 97.42547568]
 [ 75.34906654]
 [ 94.10364104]
 [ 94.67158282]
 [ 57.50569802]
 [ 85.63755977]
 [ 99.83610434]
 [ 80.32168105]
 [ 98.42249772]
 [ 60.57008451]
 [ 96.99639543]
 [ 80.4074971 ]
 [ 56.59449204]
 [ 80.49331315]
 [ 56.93775624]
 [ 99.1620716 ]
 [ 91.62747123]
 [ 75.40211201]
 [ 75.52069864]
 [ 85.12266347]
 [ 69.77573966]
 [ 94.84321492]
 [ 97.45824626]
 [ 78.36040755]
 [ 80.83657736]
 [ 97.56433721]
 [ 89.95641646]
 [ 90.66321977]
 [ 98.02618804]
 [ 84.72635379]
 [ 88.27286601]
 [ 61.44851993]
 [ 66.57249164]
 [ 63.04625432]
 [ 92.9349869 ]
 [ 87.5660627 ]
 [ 52.61889956]
 [ 98.33668167]
 [ 94.63881225]
 [ 77.44920156]
 [ 60.99916477]
 [ 79.09998144]
 [ 86.25854703]
 [ 63.6141961 ]
 [ 84.72635379]
 [116.49054381]
 [ 81.31870309]
 [122.16996164]
 [ 99.64419734]
 [ 88.16677506]
 [

In [ ]:
from sklearn.model_selection import train_test_split
X = dataSet[['Math', 'Reading']].to_numpy()
Y = dataSet['Writing'].to_numpy()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print("Training set shapes:")
print("X_train:", X_train.shape, "Y_train:", Y_train.shape)

print("\nTest set shapes:")
print("X_test:", X_test.shape, "Y_test:", Y_test.shape)


Training set shapes:
X_train: (800, 2) Y_train: (800,)

Test set shapes:
X_test: (200, 2) Y_test: (200,)


In [ ]:
def cost_function(X, Y, W):
    """
    Parameters:
    - X: Feature Matrix
    - Y: Target Matrix
    - W: Weight Matrix

    Output:
    - cost: Mean Squared Error
    """
    y_pred = np.dot(W.T, X).flatten()
    error = y_pred - Y
    cost = np.mean(error ** 2) / 2

    return cost

In [ ]:
def cost_function(X, Y, W):
    """
    Parameters:
    - X: Feature Matrix
    - Y: Target Matrix
    - W: Weight Matrix

    Output:
    - cost: Mean Squared Error
    """
    y_pred = np.dot(X, W)
    error = y_pred.flatten() - Y
    cost = np.mean(error ** 2) / 2
    return cost

X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1]).reshape(2, 1)
cost = cost_function(X_test, Y_test, W_test)
print("Cost function output:", cost)
if cost == 0:
    print("Proceed further.")
else:
    print("Something went wrong: Reimplement the cost function.")

Cost function output: 0.0
Proceed further.


In [ ]:
def gradient_descent(X, Y, W, alpha, iterations):
    """
    Perform gradient descent to optimize the parameters of a linear regression model.

    Parameters:
    - X (numpy.ndarray): Feature matrix (m x n).
    - Y (numpy.ndarray): Target vector (m x 1).
    - W (numpy.ndarray): Initial guess for parameters (n x 1).
    - alpha (float): Learning rate.
    - iterations (int): Number of iterations for gradient descent.

    Returns:
    - W_update (numpy.ndarray): Updated parameters (n x 1).
    - cost_history (list): History of cost values over iterations.
    """
    m = len(Y)
    cost_history = [0] * iterations

    for iteration in range(iterations):
        Y_pred = np.dot(X, W)
        loss = Y_pred - Y
        dw = (1 / m) * np.dot(X.T, loss)
        W = W - alpha * dw
        cost = cost_function(X, Y, W)
        cost_history[iteration] = cost

    return W, cost_history

In [ ]:
np.random.seed(0)
X = np.random.rand(100, 3)
Y = np.random.rand(100)
W = np.random.rand(3)
alpha = 0.01
iterations = 1000
final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)
print("Final Parameters:", final_params)
print("Cost History:", cost_history)

Final Parameters: [0.20551667 0.54295081 0.10388027]
Cost History: [0.10711197094660153, 0.10634880599939901, 0.10559826315680616, 0.10486012948320558, 0.1041341956428534, 0.10342025583900626, 0.1027181077540776, 0.1020275524908062, 0.10134839451441931, 0.1006804415957737, 0.1000235047554587, 0.09937739820884377, 0.09874193931205609, 0.09811694850887098, 0.09750224927850094, 0.0968976680842672, 0.09630303432313951, 0.09571818027612913, 0.09514294105952065, 0.09457715457692842, 0.09402066147216397, 0.09347330508290015, 0.09293493139511913, 0.09240538899833017, 0.09188452904154543, 0.0913722051899995, 0.09086827358260123, 0.09037259279010502, 0.08988502377398917, 0.08940542984603007, 0.08893367662855953, 0.08846963201539432, 0.08801316613342668, 0.08756415130486386, 0.08712246201010665, 0.08668797485125507, 0.08626056851623205, 0.08584012374351278, 0.08542652328745133, 0.08501965188419301, 0.0846193962181636, 0.08422564488912489, 0.08383828837978763, 0.08345721902397185, 0.08308233097530

In [ ]:
def rmse(Y, Y_pred):
    """
    Calculate the Root Mean Squared Error (RMSE).

    Parameters:
    - Y: Actual target values (1D array).
    - Y_pred: Predicted target values (1D array).

    Returns:
    - rmse: Root Mean Squared Error.
    """
    n = len(Y)
    rmse = np.sqrt(np.sum((Y - Y_pred) ** 2) / n)
    return rmse


In [ ]:
def r2(Y, Y_pred):
    """
    Calculate the R Squared (coefficient of determination) value.

    Parameters:
    - Y: Actual target values (1D array).
    - Y_pred: Predicted target values (1D array).

    Returns:
    - r2: R Squared value.
    """
    n = len(Y)
    mean_y = np.mean(Y)
    ss_total = np.sum((Y - mean_y) ** 2)
    ss_residual = np.sum((Y - Y_pred) ** 2)
    r2 = 1 - (ss_residual / ss_total)
    return r2

In [ ]:
# Main Function
def main():
    X = dataSet[['Math', 'Reading']].values
    Y = dataSet['Writing'].values
    X_mean = X.mean(axis=0)
    X_std = X.std(axis=0)
    X_normalized = (X - X_mean) / X_std
    X_train, X_test, Y_train, Y_test = train_test_split(X_normalized, Y, test_size=0.2, random_state=42)
    W = np.zeros(X_train.shape[1])
    alpha = 0.0001
    iterations = 1000
    W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)
    Y_pred = np.dot(X_test, W_optimal)
    model_rmse = rmse(Y_test, Y_pred)
    model_r2 = r2(Y_test, Y_pred)
    print("Final Weights:", W_optimal)
    print("Cost History (First 10 iterations):", cost_history[:10])
    print("RMSE on Test Set:", model_rmse)
    print("R-Squared on Test Set:", model_r2)
if __name__ == "__main__":
    main()

Final Weights: [1.06484959 1.40144515]
Cost History (First 10 iterations): [2471.6620474310935, 2471.6253575184387, 2471.5886802576224, 2471.552015644236, 2471.5153636738696, 2471.4787243421174, 2471.4420976445736, 2471.405483576834, 2471.3688821344967, 2471.332293313161]
RMSE on Test Set: 69.78693505233176
R-Squared on Test Set: -18.456124807688028
